// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqf65IdHYjfc8bBB_lpk8og8rR_9FxoE',
    appId: '1:834666561031:web:f45eccaef526bccff8b4a2',
    messagingSenderId: '834666561031',
    projectId: 'auth-project-c0921',
    authDomain: 'auth-project-c0921.firebaseapp.com',
    storageBucket: 'auth-project-c0921.appspot.com',
    measurementId: 'G-BJTLLXX80K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLA_tcVk29e1ZTcbdTp0lveioTKX9DLa8',
    appId: '1:834666561031:android:f2e5c7a20f3706f8f8b4a2',
    messagingSenderId: '834666561031',
    projectId: 'auth-project-c0921',
    storageBucket: 'auth-project-c0921.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU3qF7BVlj1JQxPGGiWEd9nrrgc3vQQN8',
    appId: '1:834666561031:ios:65922d074a3709d8f8b4a2',
    messagingSenderId: '834666561031',
    projectId: 'auth-project-c0921',
    storageBucket: 'auth-project-c0921.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU3qF7BVlj1JQxPGGiWEd9nrrgc3vQQN8',
    appId: '1:834666561031:ios:65922d074a3709d8f8b4a2',
    messagingSenderId: '834666561031',
    projectId: 'auth-project-c0921',
    storageBucket: 'auth-project-c0921.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIqf65IdHYjfc8bBB_lpk8og8rR_9FxoE',
    appId: '1:834666561031:web:d6cb935a7759d4c4f8b4a2',
    messagingSenderId: '834666561031',
    projectId: 'auth-project-c0921',
    authDomain: 'auth-project-c0921.firebaseapp.com',
    storageBucket: 'auth-project-c0921.appspot.com',
    measurementId: 'G-G4MH8LZLYG',
  );
}
